/**
 * Host half of `dsh-mobile-web`.
 *
 * Deliberately a no-op. Everything this plugin does happens in the browser:
 * the client bundle (`lib/client.js`, generated by `build.mjs` from
 * `src/mobile.css` + `src/mobile.js`) injects a gated stylesheet and a small
 * behaviour layer. Nothing needs to run on the host, no route is registered,
 * and no DSH source file is patched — so the host half contributes no surface
 * area and cannot fail a boot.
 *
 * The bundle is discovered from `package.json`'s `dsh.client` declaration
 * (`exports["./client"]`); this module exists because a `cordis.patch.yml`
 * insert has to name a loadable plugin.
 *
 * @module dsh-mobile-web
 */

/** The plugin's cordis identity. */
export const name = 'mobile-web'

/** No host services are required. */
export const inject = []

/** No host-side work to do. */
export function apply() {}
